### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by nocnokneo**
Add support for Python 3 (while retaining support for Python 2)
http://python-future.org/compatible_idioms.html#print

### CODE REVIEW

**Comment by nico** [comment]
Don't you need to add a `from __future__ import print_function` to keep things actually working on 2.7?

**Comment by nico** [comment]
Please reopen if you decide to add the import line.

**Comment by nocnokneo** [comment]
> Don't you need to add a `from __future__ import print_function` to keep things actually working on 2.7?

Added. It's [not strictly required here](https://python-future.org/compatible_idioms.html#essential-syntax-differences), but it makes sense to do anyway in case later code changes use the multiarg form of the `print` function.

**Comment by nico** [comment]
Thanks! The diff at https://github.com/nico/ninjatracing/compare/master...nocnokneo:Python3Support lgtm, but "Reopen and comment" on github is greyed out and has a tooltip that says "The Python3Support branch was force-pushed or recreated." so I don't know how to merge it. Maybe you can send a new pull request?

Sorry for the trouble!

**Comment by nocnokneo** [comment]
No problem - I created new PR #13. Thanks!

**Pull request closed without merging**
