### PR TITLE
Change target sort order to increasing

### PR DESCRIPTION
**Pull request by crogre**
This fixes issue #14 so that the unit tests pass again.

### CODE REVIEW

**Comment by nico** [comment]
Does `reverse=True` fix things too? That's maybe more readable.

Do you know what broke the tests?

**Comment by crogre** [comment]
I think PR #12 (didn't run a git bisect). At least the tests work when I revert to before that.

**Comment by nico** [comment]
Sounds plausible. @atetubou, fyi. Thanks!

**Comment by nico** [comment]
On second thought, while this fixes tests it probably undoes #12, at least partially. @atetubou, if that's the case maybe you can send a follow-up that doesn't break tests :)

**Comment by atetubou** [comment]
Thank you for noticing me.
I revised my implementation in #16

**Pull request merged**
